export default defineAppConfig({
  pages: ["pages/index/index",
    "pages/appoint/index",
    "pages/manage/index",
    "pages/settings/index",
    "pages/history/index",
    "pages/bindWechat/index",
    "pages/bindInstitutionId/index",
    "pages/privacy/index",
    "pages/shareList/index",
    "pages/contact/index",
    "pages/login/index",
    "pages/joinUs/index",
    "pages/queryForStaff/index",
    "pages/dutyRoster/index",
  ],
  tabBar: {
    color: "#000000",
    selectedColor: "#853bff",
    backgroundColor: "#ffffff",
    borderStyle: "black",
    list: [
      {
        pagePath: "pages/index/index",
        iconPath: "assets/icon/home.png",
        selectedIconPath:"assets/icon/S_home.png",
        text: "首页",
      },
      {
        pagePath: "pages/appoint/index",
        iconPath: "assets/icon/calendar.png",
        selectedIconPath:"assets/icon/S_calendar.png",
        text: "预约",
      },
      {
        pagePath: "pages/manage/index",
        iconPath: "assets/icon/chart-bar-increasing.png",
        selectedIconPath:"assets/icon/S_chart-bar-increasing.png",
        text: "管理",
      },
      {
        pagePath: "pages/settings/index",
        iconPath: "assets/icon/settings.png",
        selectedIconPath:"assets/icon/S_settings.png",
        text: "设置",
      },
    ],
  },
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#ffffff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black",
  },
});
